import { FarmerProfile, Product, Order, NotificationItem, Settlement, DeliveryAddress } from '../types';

export const INITIAL_FARMERS: FarmerProfile[] = [
  {
    id: 'farmer-1',
    user_id: 'user-f1',
    name: 'Ramesh Patil',
    photo_url: 'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?auto=format&fit=crop&w=400&q=80',
    is_verified: true,
    village: 'Niphad',
    district: 'Nashik, Maharashtra',
    location_text: 'Niphad, Nashik (12 km away)',
    farm_size_acres: 14.5,
    rating: 4.9,
    reviews_count: 128,
    farm_photos: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1592417817098-8f3d6eb19657?auto=format&fit=crop&w=800&q=80',
    ],
    bio: '3rd generation organic onion & potato farmer. Committed to zero-chemical soil conservation.',
    documents_status: 'verified',
    bank_details: {
      account_number: '•••• •••• 4921',
      ifsc: 'SBIN0001234',
      bank_name: 'State Bank of India',
      holder_name: 'Ramesh Anandrao Patil',
    },
  },
  {
    id: 'farmer-2',
    user_id: 'user-f2',
    name: 'Sunita Deshmukh',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    is_verified: true,
    village: 'Dindori',
    district: 'Nashik, Maharashtra',
    location_text: 'Dindori, Nashik (18 km away)',
    farm_size_acres: 8.0,
    rating: 4.8,
    reviews_count: 94,
    farm_photos: [
      'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80',
    ],
    bio: 'Organic fruit orchard practitioner specializing in export quality Alphonsos and Pomegranates.',
    documents_status: 'verified',
    bank_details: {
      account_number: '•••• •••• 8832',
      ifsc: 'HDFC0004321',
      bank_name: 'HDFC Bank',
      holder_name: 'Sunita Deshmukh',
    },
  },
  {
    id: 'farmer-3',
    user_id: 'user-f3',
    name: 'Prakash Jadhav',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    is_verified: true,
    village: 'Sinnar',
    district: 'Nashik, Maharashtra',
    location_text: 'Sinnar, Nashik (24 km away)',
    farm_size_acres: 22.0,
    rating: 4.7,
    reviews_count: 67,
    farm_photos: [
      'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=800&q=80',
    ],
    bio: 'Pioneer in drip-irrigated grain cultivation & natural spice curing.',
    documents_status: 'verified',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    farmer_id: 'farmer-1',
    farmer_name: 'Ramesh Patil',
    farmer_location: 'Niphad, Nashik',
    farmer_avatar: 'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?auto=format&fit=crop&w=400&q=80',
    farmer_verified: true,
    name: 'Fresh Red Onion',
    category: 'Vegetables',
    variety: 'Nashik Red Grade A',
    price_per_unit: 28,
    unit: 'kg',
    available_quantity_kg: 250,
    min_order_qty: 1,
    harvest_date: '2026-08-19',
    farming_method: 'Organic',
    description: 'Crisp, aromatic red onions harvested directly from the nutrient-rich soils of Niphad. Zero chemical pesticides used during growth cycle.',
    image_url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews_count: 54,
    is_active: true,
    is_approved: true,
    created_at: '2026-08-20T08:00:00Z',
  },
  {
    id: 'prod-2',
    farmer_id: 'farmer-1',
    farmer_name: 'Ramesh Patil',
    farmer_location: 'Niphad, Nashik',
    farmer_avatar: 'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?auto=format&fit=crop&w=400&q=80',
    farmer_verified: true,
    name: 'Organic Potato',
    category: 'Vegetables',
    variety: 'Kufri Jyoti',
    price_per_unit: 30,
    unit: 'kg',
    available_quantity_kg: 180,
    min_order_qty: 1,
    harvest_date: '2026-08-18',
    farming_method: 'Organic',
    description: 'Firm, golden organic potatoes. Ideal for curry, roasting, and fries. Harvested fresh without synthetic fertilizers.',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviews_count: 42,
    is_active: true,
    is_approved: true,
    created_at: '2026-08-20T09:15:00Z',
  },
  {
    id: 'prod-3',
    farmer_id: 'farmer-2',
    farmer_name: 'Sunita Deshmukh',
    farmer_location: 'Dindori, Nashik',
    farmer_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    farmer_verified: true,
    name: 'Farm Fresh Tomatoes',
    category: 'Vegetables',
    variety: 'Roma Vine Ripened',
    price_per_unit: 35,
    unit: 'kg',
    available_quantity_kg: 120,
    min_order_qty: 1,
    harvest_date: '2026-08-20',
    farming_method: 'Natural',
    description: 'Juicy, sun-ripened red tomatoes picked early morning. Packed with lycopene and rich natural flavor.',
    image_url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews_count: 38,
    is_active: true,
    is_approved: true,
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'prod-4',
    farmer_id: 'farmer-2',
    farmer_name: 'Sunita Deshmukh',
    farmer_location: 'Dindori, Nashik',
    farmer_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    farmer_verified: true,
    name: 'Sweet Alphonso Mangoes',
    category: 'Fruits',
    variety: 'Ratnagiri Original',
    price_per_unit: 140,
    unit: 'kg',
    available_quantity_kg: 90,
    min_order_qty: 2,
    harvest_date: '2026-08-17',
    farming_method: 'Organic',
    description: 'Naturally ripened naturally sweet Alphonso mangoes with rich aroma and thick golden pulp.',
    image_url: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=800&q=80',
    rating: 5.0,
    reviews_count: 67,
    is_active: true,
    is_approved: true,
    created_at: '2026-08-19T14:20:00Z',
  },
  {
    id: 'prod-5',
    farmer_id: 'farmer-3',
    farmer_name: 'Prakash Jadhav',
    farmer_location: 'Sinnar, Nashik',
    farmer_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    farmer_verified: true,
    name: 'Organic Indrayani Rice',
    category: 'Grains',
    variety: 'Aromatic Whole Grain',
    price_per_unit: 75,
    unit: 'kg',
    available_quantity_kg: 500,
    min_order_qty: 5,
    harvest_date: '2026-08-01',
    farming_method: 'Organic',
    description: 'Traditional aromatic soft Indrayani rice from Maharashtra farms. Unpolished to retain natural bran nutrition.',
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviews_count: 29,
    is_active: true,
    is_approved: true,
    created_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'prod-6',
    farmer_id: 'farmer-3',
    farmer_name: 'Prakash Jadhav',
    farmer_location: 'Sinnar, Nashik',
    farmer_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    farmer_verified: true,
    name: 'Pure Raw Turmeric Powder',
    category: 'Spices',
    variety: 'High Curcumin (5.2%)',
    price_per_unit: 220,
    unit: 'kg',
    available_quantity_kg: 75,
    min_order_qty: 1,
    harvest_date: '2026-07-25',
    farming_method: 'Natural',
    description: 'Sun-dried rhizomes stone-ground into vibrant yellow turmeric. Natural immunity booster with maximum curcumin content.',
    image_url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews_count: 81,
    is_active: true,
    is_approved: true,
    created_at: '2026-08-10T09:30:00Z',
  },
  {
    id: 'prod-7',
    farmer_id: 'farmer-1',
    farmer_name: 'Ramesh Patil',
    farmer_location: 'Niphad, Nashik',
    farmer_avatar: 'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?auto=format&fit=crop&w=400&q=80',
    farmer_verified: true,
    name: 'Fresh Spicy Green Chilis',
    category: 'Vegetables',
    variety: 'G4 Hot Spicy',
    price_per_unit: 45,
    unit: 'kg',
    available_quantity_kg: 85,
    min_order_qty: 1,
    harvest_date: '2026-08-20',
    farming_method: 'Standard',
    description: 'Crispy, fiery green chilis harvested daily morning. Essential for tempering authentic Indian curries.',
    image_url: 'https://images.unsplash.com/photo-1588879460618-924bc98858a7?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviews_count: 19,
    is_active: true,
    is_approved: true,
    created_at: '2026-08-20T12:00:00Z',
  },
];

export const MOCK_ADDRESSES: DeliveryAddress[] = [
  {
    id: 'addr-1',
    name: 'Ayushi Par',
    phone: '+91 98234 56789',
    street: 'Flat 402, Green Acres Apt, Gangapur Road',
    city: 'Nashik',
    state: 'Maharashtra',
    pincode: '422013',
    is_default: true,
  },
  {
    id: 'addr-2',
    name: 'Ayushi Par (Office)',
    phone: '+91 98234 56789',
    street: 'AgriTech Hub, Business Bay, College Road',
    city: 'Nashik',
    state: 'Maharashtra',
    pincode: '422005',
    is_default: false,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'AGX-8921',
    customer_id: 'cust-101',
    customer_name: 'Ayushi Par',
    customer_phone: '+91 98234 56789',
    farmer_id: 'farmer-1',
    farmer_name: 'Ramesh Patil',
    farmer_phone: '+91 98765 43210',
    delivery_address: MOCK_ADDRESSES[0],
    delivery_type: 'Express',
    items: [
      {
        product_id: 'prod-1',
        product_name: 'Fresh Red Onion',
        quantity: 2,
        unit_price: 28,
        total_price: 56,
        unit: 'kg',
        image_url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=80',
      },
      {
        product_id: 'prod-2',
        product_name: 'Organic Potato',
        quantity: 2,
        unit_price: 30,
        total_price: 60,
        unit: 'kg',
        image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
      },
    ],
    subtotal: 116,
    delivery_fee: 25,
    discount: 10,
    total_amount: 131,
    payment_method: 'UPI',
    payment_status: 'Paid',
    order_status: 'Ready',
    created_at: '2026-08-21T09:30:00Z',
    timeline: [
      { status: 'Placed', label: 'Order Placed', timestamp: '09:30 AM', completed: true, current: false },
      { status: 'Accepted', label: 'Farmer Accepted', timestamp: '09:35 AM', completed: true, current: false },
      { status: 'Preparing', label: 'Preparing Fresh Batch', timestamp: '09:50 AM', completed: true, current: false },
      { status: 'Ready', label: 'Ready for Pickup / Dispatch', timestamp: '10:15 AM', completed: true, current: true },
      { status: 'Delivered', label: 'Delivered to Doorstep', timestamp: 'Expected 11:30 AM', completed: false, current: false },
    ],
  },
  {
    id: 'AGX-8919',
    customer_id: 'cust-102',
    customer_name: 'Vikram Mehta',
    customer_phone: '+91 97112 33445',
    farmer_id: 'farmer-2',
    farmer_name: 'Sunita Deshmukh',
    delivery_address: {
      id: 'addr-3',
      name: 'Vikram Mehta',
      phone: '+91 97112 33445',
      street: 'Villa 12, Sunshine Colony, Indiranagar',
      city: 'Nashik',
      state: 'Maharashtra',
      pincode: '422009',
    },
    delivery_type: 'Standard',
    items: [
      {
        product_id: 'prod-3',
        product_name: 'Farm Fresh Tomatoes',
        quantity: 3,
        unit_price: 35,
        total_price: 105,
        unit: 'kg',
        image_url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
      },
    ],
    subtotal: 105,
    delivery_fee: 30,
    discount: 0,
    total_amount: 135,
    payment_method: 'Card',
    payment_status: 'Paid',
    order_status: 'Delivered',
    created_at: '2026-08-20T16:20:00Z',
    timeline: [
      { status: 'Placed', label: 'Order Placed', timestamp: '04:20 PM', completed: true, current: false },
      { status: 'Accepted', label: 'Farmer Accepted', timestamp: '04:30 PM', completed: true, current: false },
      { status: 'Preparing', label: 'Preparing', timestamp: '05:00 PM', completed: true, current: false },
      { status: 'Ready', label: 'Dispatched', timestamp: '05:40 PM', completed: true, current: false },
      { status: 'Delivered', label: 'Delivered', timestamp: '06:30 PM', completed: true, current: true },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: '🔔 Order Status Updated',
    message: 'Your order AGX-8921 is now READY FOR PICKUP by AGROX Partner.',
    type: 'order',
    created_at: '10 mins ago',
    is_read: false,
    group: 'Today',
  },
  {
    id: 'notif-2',
    title: '💳 Payment Received Successfully',
    message: '₹131 payment via UPI was successfully confirmed for AGX-8921.',
    type: 'payment',
    created_at: '45 mins ago',
    is_read: true,
    group: 'Today',
  },
  {
    id: 'notif-3',
    title: '🌾 Fresh Harvest Alert!',
    message: 'Sunita Deshmukh added fresh Ratnagiri Alphonso Mangoes to AGROX.',
    type: 'system',
    created_at: 'Yesterday',
    is_read: true,
    group: 'Earlier',
  },
];

export const INITIAL_SETTLEMENTS: Settlement[] = [
  {
    id: 'SET-9912',
    farmer_id: 'farmer-1',
    amount: 14280,
    date: '2026-08-20',
    status: 'Completed',
    bank_ref: 'SBI-UTR99281726',
  },
  {
    id: 'SET-9904',
    farmer_id: 'farmer-1',
    amount: 22100,
    date: '2026-08-15',
    status: 'Completed',
    bank_ref: 'SBI-UTR88371625',
  },
  {
    id: 'SET-9918',
    farmer_id: 'farmer-1',
    amount: 4280,
    date: '2026-08-21',
    status: 'Processing',
    bank_ref: 'PENDING_BANK',
  },
];
